POST http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjg5NjgyMmFlNjViZDMwYzQ4MmViOWIiLCJpYXQiOjE2MDMzNTM2MjksImV4cCI6MTYwMzQ0MDAyOX0.NbY5nmjaMfHxjiqgYnp5f3j69NgnZrCz0D31jPtyJxM
Content-Type: application/json

{
    "userId":"5f896822ae65bd30c482eb9b",
    "name": "name",
    "description": "description",
    "manufacturer":"manufacturer",
    "mainPepper": "aa",
    "imageUrl": "http://localhost:3000/images/Capture_chopin.PNG1603269558451.png",
    "heat": 10,
}

###

GET http://localhost:3000/api/sauces
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjkwMmU3MTdlZjMwNDUwZWMzODI5MDkiLCJpYXQiOjE2MDQ5OTYxMDAsImV4cCI6MTYwNTA4MjUwMH0.a1cBBZY23UmHDWDYUD_NWU5CFZWB4I9iEux0NkigWh4
###
GET http://localhost:3000/api/sauces/5f97eaf9eee46c3458f55d29
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjkwMmU3MTdlZjMwNDUwZWMzODI5MDkiLCJpYXQiOjE2MDM4ODc3MjEsImV4cCI6MTYwMzk3NDEyMX0.qLW7hhdKjX9HI3kPWAAO9vsauPc0VDU7yI3JAAjl8kE


###

DELETE http://localhost:3000/api/sauces/5fa146c0d935aa26f862fc7b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1Zjg5NjgyMmFlNjViZDMwYzQ4MmViOWIiLCJpYXQiOjE2MDQ0MDgzMjUsImV4cCI6MTYwNDQ5NDcyNX0.cRNGAbPCQAKfle9pwRjTnXJSRmsB37h5iEJgYiZjMUg
###
PUT http://localhost:3000/api/sauces/5fa146c0d935aa26f862fc7b
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1ZjkwMmU3MTdlZjMwNDUwZWMzODI5MDkiLCJpYXQiOjE2MDQ0MDg0MjcsImV4cCI6MTYwNDQ5NDgyN30.StSMC5mf45HPsimM5TIE8Nl76sA_gLfSo-x5l3JlfUo
Content-Type: application/json

{

    "name": "name",
    "description": "description3",
    "mainPepper": "aa",
    "imageUrl": "aa",
    "heat": 44,
    "likes":1,
    "dislikes":1,
    "usersLiked":["a", "a"],
    "usersDisliked":["a", "a"]

}

###
POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
    "email":"email2@gmail.com",
    "password":"mdp"

}

###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"mdp"

}
###
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"email@gmail.com",
    "password":"mdp"

}